### ISSUE TITLE
antd-mobile标签页显示不正确

### ISSUE THREAD

**Issue by zwl1619** [jinjinwa/umi-antd-mobile#1]
antd-mobile标签页官方示例是这样的：
![image](https://user-images.githubusercontent.com/13177997/48338435-9f813100-e6a0-11e8-8465-80d394c7f65f.png)

在src/pages/index/index.js文件中测试，把antd-mobile的标签页放到页面中，显示结果是这样的：
https://mobile.ant.design/components/tabs-cn/#components-tabs-demo-mutlitabs

![image](https://user-images.githubusercontent.com/13177997/48338252-22ee5280-e6a0-11e8-90f3-bfd90c5c05bf.png)
上面的那个切换tabs不显示，是哪里没写对？代码如下：
```
import React, { PureComponent } from 'react';
import { Tabs, WhiteSpace } from 'antd-mobile';


class Index extends PureComponent {
  renderContent = tab =>
    (<div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '150px', backgroundColor: '#fff' }}>
      <p>Content of {tab.title}</p>
    </div>);

  render() {
    const tabs = [
      { title: '1st Tab' },
      { title: '2nd Tab' },
      { title: '3rd Tab' },
      { title: '4th Tab' },
      { title: '5th Tab' },
      { title: '6th Tab' },
      { title: '7th Tab' },
      { title: '8th Tab' },
      { title: '9th Tab' },
    ];

    return (
      <div>
        <WhiteSpace />
        <Tabs tabs={tabs} renderTabBar={props => <Tabs.DefaultTabBar {...props} page={3} />}>
          {this.renderContent}
        </Tabs>
        <WhiteSpace />
      </div>
    );
  }

}

export default Index;
```

**Comment by jinjinwa** [comment]
你好，抱歉刚看到。因为tabbar样式覆盖问题，所以导致tabs组件显示异常。暂时可以通过自定义样式前缀来解决。https://mobile.ant.design/components/tabs-cn/  （prefixCls）后面我会更新一下。

**Comment by DDDenial** [comment]
tabs添加prefixCls [样式前缀，样式是没问题了，但是tabs切换就会有问题，tab2的内容会在tab1下显示， 各位大佬是如何解决的？

**Comment by hanfengmi** [comment]
配置tabs后，标签之间点击跳转，第一个和最后一个标签跳转不会触发componentDidMount。有人遇到这个问题吗

**Comment by rule78** [comment]
作者得花点时间维护 umi官方引作demo了

**Comment by MiaMia-Li** [comment]
> tabs添加prefixCls [样式前缀，样式是没问题了，但是tabs切换就会有问题，tab2的内容会在tab1下显示， 各位大佬是如何解决的？

+1 请问如何解决
