### ISSUE TITLE
deploy的node服务是做什么用的? 

### ISSUE THREAD

**Issue by caohaijiang** [jinjinwa/umi-antd-mobile#2]
初入门react,到umi还能循序渐进,但是到了这个demo, 顿时头大.
1. 依赖库的多个单元测试和校验了解了.
2. config.js的复杂用法,也看到了.

问题?
1. deploy这个就太难懂了,为什么要这样做? 没有明白什么意思,达到什么目的.
2. 按umi教程, 本地执行 serve ./deploy/dist 本地验证时,出现的是404错误. 咋个解决?

**Comment by jinjinwa** [comment]
1: config/config.js中，outputPath: './deploy/dist', 配置了静态文件打包到deploy文件夹。deploy中是一个部署示例。你可以执行umi build，打包静态文件。
2: serve ./deploy/dist 的前提是要有静态文件，你要先执行umi build

**Comment by caohaijiang** [comment]
明白了, 我可修改了.否则不敢乱动. 您在umi的钉钉群吗? 是否可以加一个好友? 看我头像,和钉钉头像一致.

**Comment by jinjinwa** [comment]
我在微信群，不在钉钉群。
