### ISSUE TITLE
安卓自带浏览器打开白屏

### ISSUE THREAD

**Issue by zmm2tysu** [jinjinwa/umi-antd-mobile#5]
手机：摩托罗拉
系统：4.0.4
浏览器：自带浏览器

表现：
输入地址，白屏，但是Pro的标题图标出来了；
ps：我已经把umi的targets改成andriod：4了

**Comment by jinjinwa** [comment]
也有小伙伴反应安卓4的兼容问题，应该是umi兼容问题。可以根据具体报错找找解决方案


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by zmm2tysu** [comment]
暂时放弃安卓4了先
