### ISSUE TITLE
api请求都是返回相同的html

### ISSUE THREAD

**Issue by gocse** [jinjinwa/umi-antd-mobile#6]
本地开发时将`https://hmj.jahwaec.com`修改`localhost:8099`返回请求都是html页面，即使在mock文件下创建mock文件也不行。

**Comment by jinjinwa** [comment]
可参考umi官方文档的mock用法


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by jinjinwa** [comment]
关闭


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
