### ISSUE TITLE
项目中是通过什么组件将Less中的px自动转成rem的啊？

### ISSUE THREAD

**Issue by felix-he** [jinjinwa/umi-antd-mobile#7]
求教：项目中是通过什么组件将Less中的px自动转成rem的啊？

**Comment by jinjinwa** [comment]
hd高清解决方案，umi文档有写


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by jinjinwa** [comment]
不是bug


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
