### ISSUE TITLE
umi配置“define”不生效

### ISSUE THREAD

**Issue by Ding-Jun** [jinjinwa/umi-antd-mobile#8]
将define配置加入不生效， 相同的配置在antd-pro脚手架是生效的

"define": {
  "process.env.TEST": 1,
  "USE_COMMA": 2,
  },

**Comment by jinjinwa** [comment]
我试了一下是生效的哦。在config.js中
define: {
    'process.env.PATH_TYPE': 'test',
  }

**Comment by fancyluo88** [comment]
> 将define配置加入不生效， 相同的配置在antd-pro脚手架是生效的
> 
> "define": {
> "process.env.TEST": 1,
> "USE_COMMA": 2,
> },

页面中直接使用USE_COMMA 而不是process.env.USE_COMMA，不知道你是不是这个问题
