### ISSUE TITLE
Echart上字体显示很小

### ISSUE THREAD

**Issue by lhy58** [jinjinwa/umi-antd-mobile#9]

**Comment by jinjinwa** [comment]
跟第三方库一起使用不建议开启hd高清方案


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by lhy58** [comment]
请问怎么取消高清方案的显示,在代码上没找着您是怎么改变html的fontSize的大小以及meta的scale

**Comment by jinjinwa** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    https://umijs.org/zh/plugin/umi-plugin-react.html#hd设置hd：true
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                jinjinwa0
                            
                    
                        
                            
                                    jinjinwa0@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年04月24日 13:59，lhy58<notifications@github.com> 写道： 


请问怎么取消高清方案的显示,在代码上没找着您是怎么改变html的fontSize的大小以及meta的scale



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
